### ISSUE TITLE
NameError: uninitialized constant Module::ActiveSupport

### ISSUE THREAD

**Issue by cekediz** [boltops-tools/ufo#117]
Greetings.

After upgrading to 5.0.2 from 4.5.11, when trying to run `ufo` or `bundle exec ufo` I got this error:
```
bundler: failed to load command: ufo (/var/app/current/vendor/bundle/ruby/2.6.0/bin/ufo)
NameError: uninitialized constant Module::ActiveSupport
  /var/app/current/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/module/deprecation.rb:21:in `deprecate'
  /var/app/current/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/class/delegating_attributes.rb:26:in `<class:Class>'
  /var/app/current/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/class/delegating_attributes.rb:6:in `<top (required)>'
  /var/app/current/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/class.rb:2:in `require'
  /var/app/current/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/class.rb:2:in `<top (required)>'
  /var/app/current/vendor/bundle/ruby/2.6.0/gems/ufo-5.0.2/lib/ufo.rb:4:in `require'
  /var/app/current/vendor/bundle/ruby/2.6.0/gems/ufo-5.0.2/lib/ufo.rb:4:in `<top (required)>'
  /var/app/current/vendor/bundle/ruby/2.6.0/gems/ufo-5.0.2/exe/ufo:11:in `require'
  /var/app/current/vendor/bundle/ruby/2.6.0/gems/ufo-5.0.2/exe/ufo:11:in `<top (required)>'
  /var/app/current/vendor/bundle/ruby/2.6.0/bin/ufo:23:in `load'
  /var/app/current/vendor/bundle/ruby/2.6.0/bin/ufo:23:in `<top (required)>'
```

Modifying `ufo-5.0.2/lib/ufo.rb` as follows seems to have solved the issue for me:
```
$:.unshift(File.expand_path('../', __FILE__))
require 'active_support' #Added
require 'active_support/core_ext/class'
```

This is with Ruby 2.6.6, Rails 4.2.11 (ancient, yes :D) on Alpine/Debian.

**Comment by tongueroo** [comment]
Fixed in https://github.com/boltops-tools/ufo/pull/122
