### ISSUE TITLE
Getting an error with new version of activesupport

### ISSUE THREAD

**Issue by fedepazos95** [boltops-tools/ufo#121]
Hi, from today I started to get an error with the ufo docker build command

```
/usr/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
	from /usr/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:103:in `backend='
	from /usr/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
	from /usr/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:11:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/duration.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/core_ext/time/calculations.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/core_ext/string/conversions.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/core_ext/string.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/render_me_pretty-0.8.3/lib/render_me_pretty.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/ufo-4.6.3/lib/ufo.rb:8:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/ufo-4.6.3/exe/ufo:11:in `<top (required)>'
	from /usr/bin/ufo:23:in `load'
	from /usr/bin/ufo:23:in `<main>'
```

I've checked that gem and it seems that the version 7.0.0 was released yesterday
Installing a previous version of activesupport solved it temporaly

**Comment by tongueroo** [comment]
Thanks for the report. Fixed.
